### ISSUE TITLE
Insert console.log on the next line

### ISSUE THREAD

**Issue by yngvarr992** [LuisEGR/console-log-vscode#1]
Hello! I've found your extension very useful, thank you for that! Is there any chance of adding an option to insert console.log on the next line after the variable? That would be useful for logging newly declared variable. Thanks!

**Comment by LuisEGR** [comment]
This is implemented in the v0.0.6 and it's now available!

option + - => insert after
option + shift + - => insert before

You can toggle this two commands by setting the configuration option `invertPosition` to `true`
