### ISSUE TITLE
Is this plugin working?  

### ISSUE THREAD

**Issue by zipzit** [LuisEGR/console-log-vscode#10]
Its not totally clear on how this is supposed to be working.  

I'm assuming we :

1. highlight variable or object of interest in vscode 
2. Press the F1 key to get the View --> Command Pallet modal to pop up. 
3. Select either Console.log or Console.log.before to generate a `console.log("item: ", item)` line of code.

Is that right? If so, this is a total fail.  I'm not getting anything at all.  
I verified the plugin is installed and enabled.
I've rebooted VS code via F1 --> View --> Command Pallet modal --> Developer: Reload Window

Nothing.  I get not a thing.  Am I doing this right?  

I'm using VSCode 
Version: 1.63.2
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:39:46.686Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.11.0-43-generic

**Comment by LuisEGR** [comment]
It looks like an issue that vscode had, when sometimes it doesn't get the extension enabled, It happened to me also sometime, but now it looks like they fixed that
