### ISSUE TITLE
Support for JSX & TSX

### ISSUE THREAD

**Issue by r0skar** [LuisEGR/console-log-vscode#3]
https://github.com/LuisEGR/console-log-vscode/blob/8724ff18c8157c0a5e6dae5574cda1256136ed29/extension.js#L14

Hi. I was wondering if you could add `javascriptreact` aswell as`typescriptreact` to enable the extension for JSX and TSX files?

**Comment by LuisEGR** [comment]
This is implemented in the v0.0.6 and it's available now!
