### ISSUE TITLE
Command 'Console.log.before' resulted in an error (command 'extension.clogBefore' not found)

### ISSUE THREAD

**Issue by matiasg77** [LuisEGR/console-log-vscode#7]
I have this problem when I press F1 - Console.log.before

vscode version: 1.48.2
Console Log version: 0.0.8

**Comment by LuisEGR** [comment]
It looks like an issue that vscode had, when sometimes it doesn't get the extension enabled, It happened to me also sometime, but now it looks like they fixed that
